### ISSUE TITLE
Why Examples use typecheck.macro as node_module?

### ISSUE THREAD

**Issue by khg0712** [vedantroy/typecheck.macro#9]
@vedantroy 
Why examples use code of this repo?
1. It increase the number of managing point.
    1. When the version of `typecheck.macro` updates, then the vesion of example dependency should be updated too.
2. Memories are wasted because of duplicated resources.

In my opinion, It is better to use compiled source like [vue](examples/modal/index.html) or other repos?

**Comment by vedantroy** [comment]
I don't think the examples use typecheck.macro from node_modules? It says `from "typecheck.macro";` in https://github.com/vedantroy/typecheck.macro/blob/master/example/src/complex.ts.

Which file imports from node_modules?

**Edit**: I think I misunderstood your question. Can you clarify what the issue is?

**Comment by khg0712** [comment]
@vedantroy 
In this project, example uses `typecheck.macro` from node dependency.
I suggest you to use your library in example as not a package but local source.

**Comment by khg0712** [comment]
@vedantroy 
I think I understood your intention about example.
Did you intent that It can be worked by copy and paste?
But It doesn't look so good to me. but It is ok to you I'll close my issue :)

**Comment by vedantroy** [comment]
Ahh yes, the intent was to be able to download the example and run it with 0 configuration :smile:
